# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XS7_GMZjr9vxXzV2ZhgEEeWiJXVr1lpb
"""

import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt

def lnp_kinetics(t, y, k1, k2):
    """
    Ordinary differential equations for lipid nanoparticle structural transitions:
    C_cub -> C_int -> C_lam
    """
    C_cub, C_int, C_lam = y
    dC_cub_dt = -k1 * C_cub
    dC_int_dt = k1 * C_cub - k2 * C_int
    dC_lam_dt = k2 * C_int
    return [dC_cub_dt, dC_int_dt, dC_lam_dt]

# Initial molar fractions [Cubosomes, Intermediate State, Lamellar Vesicles]
y0 = [1.0, 0.0, 0.0]
t_span = (0, 50)
t_eval = np.linspace(0, 50, 200)

# Kinetic rate constants representing membrane interaction and phase change
k1 = 0.15  # Rate of cubosome breakdown
k2 = 0.08  # Rate of lamellar conversion

# Solve the differential equation system
solution = solve_ivp(lnp_kinetics, t_span, y0, args=(k1, k2), t_eval=t_eval)

# Generate the plot
plt.figure(figsize=(10, 5))
plt.plot(solution.t, solution.y[0], label='Intact Cubosomes ($C_{cub}$)', color='#008080', linewidth=2.5)
plt.plot(solution.t, solution.y[1], label='Intermediate Mixed State ($C_{int}$)', color='#FF8C00', linewidth=2.5)
plt.plot(solution.t, solution.y[2], label='Lamellar Vesicles ($C_{lam}$)', color='#6A5ACD', linewidth=2.5)

plt.title('LNP Structural Phase Transition Kinetics\n(Based on DOI: 10.1021/acs.jpcb.4c06060)', fontsize=12, fontweight='bold')
plt.xlabel('Interaction Time (Arbitrary Units)', fontsize=11)
plt.ylabel('Normalized Concentration Fraction', fontsize=11)
plt.legend(frameon=True, facecolor='#f8f9fa')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt

def lnp_kinetics(t, y, k1, k2):
    C_cub, C_int, C_lam = y
    dC_cub_dt = -k1 * C_cub
    dC_int_dt = k1 * C_cub - k2 * C_int
    dC_lam_dt = k2 * C_int
    return [dC_cub_dt, dC_int_dt, dC_lam_dt]

# Time parameters
t_span = (0, 50)
t_eval = np.linspace(0, 50, 200)
y0 = [1.0, 0.0, 0.0]

# Define conditions based on membrane properties
conditions = {
    "Baseline ($k_1=0.15, k_2=0.08$)": (0.15, 0.08, '#008080'),
    "Fluid Membrane ($k_1=0.30, k_2=0.12$)": (0.30, 0.12, '#FF4500'),
    "Rigid / Cholesterol-Rich ($k_1=0.05, k_2=0.03$)": (0.05, 0.03, '#4682B4')
}

# Plotting comparative kinetics
fig, axes = plt.subplots(1, 3, figsize=(15, 5), sharey=True)

for i, (label, (k1, k2, color)) in enumerate(conditions.items()):
    sol = solve_ivp(lnp_kinetics, t_span, y0, args=(k1, k2), t_eval=t_eval)

    # Plotting curves
    axes[i].plot(sol.t, sol.y[0], label='Intact Cubosomes ($C_{cub}$)', color=color, linewidth=2)
    axes[i].plot(sol.t, sol.y[1], label='Intermediate ($C_{int}$)', color='#FF8C00', linestyle='--', linewidth=1.5)
    axes[i].plot(sol.t, sol.y[2], label='Lamellar ($C_{lam}$)', color='#6A5ACD', linestyle=':', linewidth=1.5)

    axes[i].set_title(label, fontsize=10, fontweight='bold')
    axes[i].set_xlabel('Interaction Time (a.u.)', fontsize=9)
    if i == 0:
        axes[i].set_ylabel('Normalized Concentration Fraction', fontsize=9)
    axes[i].grid(True, linestyle='--', alpha=0.5)
    axes[i].legend(fontsize=8, frameon=True)

plt.suptitle('Comparative LNP Phase Transition Dynamics Across Membrane Types\n(DOI: 10.1021/acs.jpcb.4c06060)', fontsize=12, fontweight='bold', y=1.03)
plt.tight_layout()
plt.show()